-- Script was generated by Devart dbForge Studio Express for MySQL, Version 5.0.97.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 06-Nov-12 4:23:50 PM
-- Server version: 5.5.28
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE orphanage;

--
-- Definition for table campaign
--
DROP TABLE IF EXISTS campaign;
CREATE TABLE campaign (
  id INT(11) NOT NULL AUTO_INCREMENT,
  organizer VARCHAR(255) DEFAULT NULL,
  `date` TIME DEFAULT NULL,
  name VARCHAR(255) DEFAULT NULL,
  details TEXT DEFAULT NULL,
  results TEXT DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table location
--
DROP TABLE IF EXISTS location;
CREATE TABLE location (
  id INT(11) NOT NULL AUTO_INCREMENT,
  location VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table users
--
DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  first_name VARCHAR(255) DEFAULT NULL,
  last_name VARCHAR(255) DEFAULT NULL,
  email VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) DEFAULT NULL,
  phone_number VARCHAR(255) DEFAULT NULL,
  profile_picture VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table orphanage
--
DROP TABLE IF EXISTS orphanage;
CREATE TABLE orphanage (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  details VARCHAR(255) DEFAULT NULL,
  location_id INT(11) NOT NULL,
  address VARCHAR(255) DEFAULT NULL,
  profile_image VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT orphanage_location FOREIGN KEY (location_id)
    REFERENCES location(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table activities
--
DROP TABLE IF EXISTS activities;
CREATE TABLE activities (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  picture_link VARCHAR(255) DEFAULT NULL,
  orphanage_id INT(255) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT activitie_orphanage FOREIGN KEY (orphanage_id)
    REFERENCES orphanage(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table bank
--
DROP TABLE IF EXISTS bank;
CREATE TABLE bank (
  id INT(11) NOT NULL AUTO_INCREMENT,
  bank VARCHAR(255) DEFAULT NULL,
  bank_account VARCHAR(255) DEFAULT NULL,
  account VARCHAR(255) DEFAULT NULL,
  orphanage_id INT(11) DEFAULT NULL,
  cf VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT bank_orphanage FOREIGN KEY (orphanage_id)
    REFERENCES orphanage(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table child
--
DROP TABLE IF EXISTS child;
CREATE TABLE child (
  id INT(11) NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(255) DEFAULT NULL,
  last_name VARCHAR(255) DEFAULT NULL,
  birthday TIME DEFAULT NULL,
  profile_picture VARCHAR(255) DEFAULT NULL,
  orphanage_id INT(255) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT child_orphanage FOREIGN KEY (orphanage_id)
    REFERENCES orphanage(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table contact
--
DROP TABLE IF EXISTS contact;
CREATE TABLE contact (
  id INT(11) NOT NULL AUTO_INCREMENT,
  contact VARCHAR(255) DEFAULT NULL,
  orphanage_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT contact_orphanage FOREIGN KEY (orphanage_id)
    REFERENCES orphanage(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table investment
--
DROP TABLE IF EXISTS investment;
CREATE TABLE investment (
  id INT(11) NOT NULL AUTO_INCREMENT,
  investor VARCHAR(255) DEFAULT NULL,
  investment_time TIME DEFAULT NULL,
  orphanage_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT investment_orphanage FOREIGN KEY (orphanage_id)
    REFERENCES orphanage(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table need
--
DROP TABLE IF EXISTS need;
CREATE TABLE need (
  id INT(11) NOT NULL AUTO_INCREMENT,
  need VARCHAR(255) DEFAULT NULL,
  orphanage_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT need_orphanage FOREIGN KEY (orphanage_id)
    REFERENCES orphanage(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table talent
--
DROP TABLE IF EXISTS talent;
CREATE TABLE talent (
  id INT(11) NOT NULL AUTO_INCREMENT,
  talent VARCHAR(11) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  pciture_link VARCHAR(255) DEFAULT NULL,
  child_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT talent_child FOREIGN KEY (child_id)
    REFERENCES child(id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

-- 
-- Dumping data for table campaign
--
-- Table scooby.campaign does not contain any data (it is empty)

-- 
-- Dumping data for table location
--
-- Table scooby.location does not contain any data (it is empty)

-- 
-- Dumping data for table users
--
-- Table scooby.users does not contain any data (it is empty)

-- 
-- Dumping data for table orphanage
--
-- Table scooby.orphanage does not contain any data (it is empty)

-- 
-- Dumping data for table activities
--
-- Table scooby.activities does not contain any data (it is empty)

-- 
-- Dumping data for table bank
--
-- Table scooby.bank does not contain any data (it is empty)

-- 
-- Dumping data for table child
--
-- Table scooby.child does not contain any data (it is empty)

-- 
-- Dumping data for table contact
--
-- Table scooby.contact does not contain any data (it is empty)

-- 
-- Dumping data for table investment
--
-- Table scooby.investment does not contain any data (it is empty)

-- 
-- Dumping data for table need
--
-- Table scooby.need does not contain any data (it is empty)

-- 
-- Dumping data for table talent
--
-- Table scooby.talent does not contain any data (it is empty)

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;